### PR TITLE
BTHAB-82: Increase supported line items to 50

### PR DESCRIPTION
**Pull request by olayiwola-compucorp**
## Overview
Previously only 10 line items can be added to a contribution from the contribution create/edit screen, we are extending this to 50.

## Before
Only 10 line items can be created
image

## After
Upto 30 line items can be created
afafaf

## Technical details

See :https://github.com/compucorp/lineitemedit/pull/3#issuecomment-1483213579

## Comment
This PR will also be sent to the module maintainer https://lab.civicrm.org/extensions/lineitemedit

### CODE REVIEW

**Comment by jamienovick** [comment]
@olayiwola-compucorp based on your PR do you think there would be any reason not to make it 100 or 500? I'm just wondering whether 30 is there for a reason and just so we don't need to come back here again in 2 years time as a client hits a bug for a big order! Thoughts?

**Comment by omarabuhussein** [comment]
So here are my thoughts:

1- All CiviCRM line items (stored inside the civicrm_line_item table) should have their price_field_id and price_field_value_id fields set.

2- CiviCRM has a default price set called `default_contribution_amount`  (that is also reserved, so it only shows up from the API or db but not from the UI) , and a single default price field under it called `contribution_amount`, and under that field a default price field value also called "contribution_amount", all of them have the id = 1 in the database.

3- If you create a contribution on Civi using the "Financial type" option, then the contribution will only have a single line item, and Civi by default will use the default price field and price field value from above (`contribution_amount`) for this line item.

4- Where if you use the price set option on the Contribution form, then each line item in that price set will take its price_field_id and price_field_value_id from the price set that is selected.


Now if you want to add new line item to any contribution, whither it was created by the "financial type" option or the "price set" option,  then this new line item should have its price_field_id and price_field_value_id fields set to something, but there is a problem, the civicrm_line_item table  has the following composite unique key  (entity_id, entity_table, contribution_id, price_field_value_id, price_field_id), which means that both  "price_field_value_id" and "price_field_id" can only be used by a single line item on any given contribution, so any new line item we create should use different price_field_id and price_field_value_id than any other line item that exists on the contribution. 

Because of the composite unique key on the line item table, the lineitemeditor extension creator seems to have decided to create 10 extra price fields and price field values under the default CiviCRM price set `contribution_amount` (the one I talked about above), and so any new line item you add to any contribution will use one of these 10 price fields, now why 10? I think it was arbitrarily decided, given at the end each price field and price field value are stored in the database, and so you will need to decide on a limit and just go with. 

What you did above @olayiwola-compucorp , seems to be adding another 20 price fields in extra to the existing 10, under the hope that 30 should be enough for BTHAB use cases or any of our other clients use cases, which does not seem bad to me (I mean given the circumstances, but in reality the way Civi uses price sets and price fields is just weird).  So given all of that @jamienovick ,  the max limit I am fine with is probably 50, I think 100 or 500 is just a bit too much, and might have a negative impact on the system performance.

**Comment by jamienovick** [comment]
50 seems fine to me if that's not too much additional work to implement

**Comment by omarabuhussein** [comment]
@olayiwola-compucorp also I see there is a comment that says "PR will also be created towards the core extension" , is this still valid ? if so can you leave more details about what this core PR will be about ?

**Comment by olayiwola-compucorp** [comment]
> @olayiwola-compucorp also I see there is a comment in the PR description that says "PR will also be created towards the core extension" , is this still valid ? if so can you leave more details about what this core PR will be about ?

Corrected that, I meant the module maintainer.

**Comment by olayiwola-compucorp** [comment]
The core PR has been merged to master  https://lab.civicrm.org/extensions/lineitemedit/-/merge_requests/74

Closing this PR

**Pull request closed without merging**
